# Generated by Django 2.2.3 on 2019-08-09 18:18

from django.db import migrations
import django_extensions.db.fields

from bank.models import Banks


def migrate_data_forward(apps, schema_editor):
    for instance in Banks.objects.all():
        print("Generating slug for ", instance)
        instance.save() # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass

#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('bank', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.AddField(
#             model_name='banks',
#             name='slug',
#             field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name', unique=True),
#         ),
#     ]


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(null=True, default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]