# Generated by Django 2.2.3 on 2019-08-09 18:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_banks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
